# Import necessary parts from the Flask library
from flask import Flask, render_template
import datetime # To get the current time

# Create a Flask application instance
app = Flask(__name__)

# Define what happens when someone visits the main page (e.g., http://localhost:5000/)
@app.route('/')
def home():
    # Get the current time
    now = datetime.datetime.now()
    current_time_str = now.strftime("%Y-%m-%d %H:%M:%S") # Format the time nicely

    # Render the 'index.html' template and pass dynamic data to it
    return render_template(
        'index.html',
        title="Dynamic Docker App",
        heading="Welcome to My Dynamic Docker App!",
        message="This page was generated by a Python Flask application.",
        current_time=current_time_str
    )

# This part runs the Flask application if this script is executed directly
if __name__ == '__main__':
    # Run the app on all available network interfaces (0.0.0.0) and port 5000
    # debug=True means it will show more information if there are errors (good for development)
    app.run(host='0.0.0.0', port=5000, debug=True)

